import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'ess.othain.com',
  appName: 'OthainESS',
  webDir: 'build',
  // Generated by Capacitor when syncing the @transistorsoft/capacitor-background-geolocation plugin
  plugins: {
    BackgroundGeolocation: {}
  }
};

export default config;
